# Generated by Django 3.2.12 on 2022-02-25 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 7, 18, 3, 440783), verbose_name='date published'),
        ),
    ]
