# Generated by Django 3.2.12 on 2022-02-26 05:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220226_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.series', verbose_name='Series'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 26, 5, 0, 24, 38770), verbose_name='date published'),
        ),
    ]
